#ifndef ELTEXIRC_SERVER_IRCLIMITS_H
#define ELTEXIRC_SERVER_IRCLIMITS_H

#define IRC_NICK_MAX_LENGTH 63
#define IRC_NICK_BUF_SIZE (IRC_NICK_MAX_LENGTH + 1
#define IRC_CHANNAME_MAX_LENGTH 63
#define IRC_CHAN_BUF_SIZE (IRC_CHANNAME_MAX_LENGTH + 1)
#define IRC_MSG_MAX_LENGTH 512
#define IRC_HOST_MAX_LENGTH 200

#endif  // ELTEXIRC_SERVER_IRCLIMITS_H